#!/bin/bash
# Copyright (c) 2016-2020 The Hush developers
# Released under the GPLv3

# set working directory to the location of this script
# readlink -f does not always exist
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
DIR="$( cd "$( dirname "$( readlink "${BASH_SOURCE[0]}" )" )" && pwd )"
cd $DIR

NAME=HUSH3

CLI=${KOMODOCLI:-./komodo-cli}
if [ -f $CLI ]; then
    $CLI -ac_name=$NAME "$@"
else
    # We prefix our binary when installed
    # system wide on Debain systems, to prevent clashes,
    # because we are classy like that. Fuck jl777, The KYC Traitor.
    CLI=hush-komodo-cli
    $CLI -ac_name=$NAME "$@"
fi
