#!/bin/bash
# Copyright (c) 2016-2020 The Hush developers
# Released under the GPLv3

# set working directory to the location of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

NAME=HUSHT

./komodo-tx -ac_name=$NAME "$@"
