#!/bin/bash
# Copyright (c) 2016-2021 The Hush developers
# Distributed under the GPLv3 software license, see the accompanying
# file COPYING or https://www.gnu.org/licenses/gpl-3.0.en.html

# set working directory to the location of this script
DIR="$( cd "$( dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
cd $DIR
DIR="$( cd "$( dirname "$( readlink "${BASH_SOURCE[0]}" )" )" && pwd )"
cd $DIR

# TESTING VALUES, DO NOT USE EXCEPT FOR DEVELOPMENT
NAME=HUSH3T
# this corresponds to FR address RHushEyeDm7XwtaTWtyCbjGQumYyV8vMjn
SCRIPT=76a9145eb10cf64f2bab1b457f1f25e658526155928fac88ac

# Hush was and will always be:
# The First Pure Sapling Zcash Protocol chain!
SAPLING=1

# Chain parameters
ERAS=3
BLOCKTIME=150
# 6250000 - (sprout pool at block 500,000)
SUPPLY=6178674
FOUNDERS=1
REWARD=0,1125000000,562500000
PERC=11111111
HALVING=129,340000,840000
END=128,340000,5422111
CLIENTNAME=GoldenSandtrout
SEEDNODE=1.2.3.4
CCLIB=hush3

# CryptoConditions/Custom Consensus params
FAUCET=228
HEIR=234
CHANNEL=235
ORACLE=236
GATEWAY=241
CCENABLE=$FAUCET,$HEIR,$CHANNEL,$ORACLE,$GATEWAY

# jl777 dishonored his village and so Duke The Elder journeys on
# with the True Extreme Privacy Cypherpunks
KMD=${KOMODOD:-./komodod}
$KMD -ac_name=$NAME           \
     -ac_sapling=$SAPLING     \
     -ac_reward=$REWARD       \
     -ac_halving=$HALVING     \
     -ac_end=$END             \
     -ac_eras=$ERAS           \
     -ac_blocktime=$BLOCKTIME \
     -ac_cc=2                 \
     -ac_ccenable=$CCENABLE   \
     -ac_founders=$FOUNDERS   \
     -ac_supply=$SUPPLY       \
     -ac_perc=$PERC           \
     -clientname=$CLIENTNAME  \
     -ac_cclib=$CCLIB         \
     -ac_script=$SCRIPT  "$@"
