#!/bin/bash
# Copyright (c) 2016-2021 The Hush developers

# set working directory to the location of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

NAME=HUSH3T

CLI=${KOMODOCLI:-./komodo-cli}
$CLI -ac_name=$NAME "$@"
